---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
unzip("activity.zip")
data<-read.csv("activity.csv")
head(data)
```


## What is mean total number of steps taken per day?

```{r}
sdata<-split(data, data$date)
stepsPerDay<-sapply(sdata, function(x) sum(x$steps, na.rm=TRUE))
hist(stepsPerDay, breaks=25, ylab="Count")
mean(stepsPerDay)
median(stepsPerDay)
```

## What is the average daily activity pattern?

```{r}
sdata2<-split(data,data$interval)
stepsPerInterval<-sapply(sdata2, function(x) mean(x$steps, na.rm=TRUE))
interval<-data$interval
intervalUnique<-unique(interval)
plot(intervalUnique,stepsPerInterval, type="l", xlab="5 min interval ID", ylab="Steps across all days")
which.max(stepsPerInterval)
```


## Imputing missing values

```{r}

data2<-data
nas<-is.na(data2$steps)
sdata3<-split(data,data$interval)
stepsPerInterval<-sapply(sdata3, function(x) mean(x$steps, na.rm=TRUE))
data2$steps[nas]<-stepsPerInterval[as.character(data2$interval[nas])]
#data2 now contains missing values filled with mean value


#this sections splits the data2 and gives mean and median
sdata<-split(data2, data2$date)
stepsPerDay<-sapply(sdata, function(x) sum(x$steps, na.rm=TRUE))
hist(stepsPerDay, breaks=25, ylab="Count")
mean(stepsPerDay)
median(stepsPerDay)

```

## Are there differences in activity patterns between weekdays and weekends?

```{r}
library(lattice)
wd<-weekdays(as.Date(data2$date))
for (i in 1:length(wd)){
  if(wd[i]=="Monday"||wd[i]=="Tuesday"||wd[i]=="Wednesday"||wd[i]=="Thursday"||wd[i]=="Friday"){
    wd[i]<-"Weekday"
  }
  else
    wd[i]<-"Weekend"
}

data3<-cbind(wd,data2)
dataByDay<-aggregate(data3$steps,by=list(data3$interval, data3$wd), FUN=mean)
xyplot(dataByDay$x~dataByDay$Group.1|dataByDay$Group.2, type="l", xlab="5 min ```
